### ISSUE TITLE
Image not showing up when shared

### ISSUE THREAD

**Issue by advenchatera** [billerickson/Shared-Counts-Pinterest-Image#3]
I am having a TON of issues with both shared counts and the pinterest image add-on. I have troubleshooted my wordpress by deleting cache, deactivating plugins, changing to a basic theme, etc. And NOTHING worked. 

I finally got the pinterest image to show up when clicking the pinterest share button (don't know what I even did!), but it was showing up as a square instead of a rectangle. Then, I realized it was the wrong image, went in to put in a different image in the pinterest sharing image box, updated, and then I'm back to the pinterest image not displaying when I click the pin button. It gives me that broken image icon in the upper left corner.

What am I doing wrong? Now I've gone back to check on it again after writing this and an image is appearing again, but yet again it's a square instead of a rectangle. Is that not changeable? The image is a rectangle and it is being cropped off..

**Comment by billerickson** [comment]
The Shared Counts - Pinterest Image extension uses the full image size. What you might be seeing is the way Pinterest presents that image in the popup. Have you tried actually pinning the image, then viewing the pin to see how it looks?

**Comment by advenchatera** [comment]
I did do that. I downloaded another pinterest image plug-in instead, but it
is also doing the same thing, so now I have reached out to pinterest.
Thanks!
